### ISSUE TITLE
Is there a way to ensure specific RPS

### ISSUE THREAD

**Issue by mityukov** [clue/reactphp-mq#26]
Hi,

So far, I could only find a way to ensure max number of concurrent jobs. 

Is there a way ensure that, say, "no more than 7 requests per second" limit is conformed?

**Comment by SimonFrings** [comment]
Hey @mityukov, thanks for bringing this up :+1:

Do you only want to execute 7 requests at one time (as a maximum value of concurrent requests) or start handling 7 requests every second?  The second case could lead to quite an amount of requests being handled at the same time, depending on how long each one takes (but that's what @reactphp is all here for, so no big problem there ^^). 

Can you give me more insights on your use case and why you want to limit the requests per second?
A ticket with a similar topic also exists: #14.

There's no implementation for this at the moment but if I remember correctly @clue build a prototype for this feature a while back for an commercial project. So let me summon the almighty @clue ^^

**Comment by mityukov** [comment]
@SimonFrings 
> Can you give me more insights on your use case and why you want to limit the requests per second?
A ticket with a similar topic also exists: https://github.com/clue/reactphp-mq/issues/14.

There's an External API I need to interact with and they have this 7 RPS restriction. If you max it out once or twice — you get 429 response, no biggie… But if it's maxed out quite often — they may completely disable the endpoint for you (re-enabling would require communicating with the support team, so, it would take time).

Currently, I do those requests directly in php-fpm, but keep number of requests (fired within current second) in a Redis key = and if it's 7 already — I just pause the execution. But this doesn't make it FIFO at all…

Ideally, I'd like to have a separate long-running process running on My server, kind of "API Proxy", where I can set my own limits, and this process will actually request the external API, respecting the RPS, maybe, having a pool of HTTP connections with keep-alive and so on. Is there anything like this already available for ReactPHP or, maybe, Swool? I am maybe using wrong terms for is, when trying to find on Google (like it was when I didn't know the "Token bucket" term, and then, after I knew it — the searches became much more resultative =)

**Comment by clue** [comment]
> > Can you give me more insights on your use case and why you want to limit the requests per second?
> > A ticket with a similar topic also exists: #14.
> 
> There's an External API I need to interact with and they have this 7 RPS restriction. If you max it out once or twice — you get 429 response, no biggie… But if it's maxed out quite often — they may completely disable the endpoint for you (re-enabling would require communicating with the support team, so, it would take time).

Sounds like a perfectly valid use case for this package! This specific feature is currently outstanding integration into this package and is already tracked in https://github.com/clue/reactphp-mq/issues/14 (and also https://github.com/clue/reactphp-flux/issues/17).

Like @SimonFrings mentioned, this is indeed possible using this project's architecture and I've indeed used this in a number of client projects already. I'd love to work out a reusable API once we have a better understanding of how much we can actually reuse in here, but so far this always turned out to be a rather individual integration. If you need this for a commercial project and you want to help sponsor this feature, feel free to reach out and I'm happy to take a look.

I hope this helps! :+1:
